version: "3.9"
services:
  frontend:
    build: frontend
    hostname: frontend
    environment:
      - HOST
  backend:
    build: backend
    hostname: backend
    environment:
      - HOST
  nginx:
    image: nginx:latest
    ports:
      - "10301:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"

